name: 📚 カリキュラム・教材のフィードバック
description: カリキュラムや教材についてのご意見・感想をお聞かせください
title: "[CURRICULUM] "
labels: ["curriculum", "feedback", "education"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## カリキュラム・教材のフィードバック
        
        AI Creator Labのカリキュラムや教材について、ご意見・ご感想をお聞かせください。
        皆様からのフィードバックをもとに、より良い学習体験を提供していきます。

  - type: dropdown
    id: course-type
    attributes:
      label: 対象コース
      description: どのコースについてのフィードバックですか？
      options:
        - 大人向けAIスクール（3日間集中講座）
        - AI Kids Lab - ビギナーコース（小1-3年生）
        - AI Kids Lab - ジュニアコース（小4-6年生）
        - AI Kids Lab - アドバンスコース（中高生）
        - 法人向け研修プログラム
        - オンライン教材・コンテンツ
        - 全般
    validations:
      required: true

  - type: dropdown
    id: feedback-type
    attributes:
      label: フィードバックの種類
      description: どのようなフィードバックですか？
      options:
        - 良い点・評価できる点
        - 改善提案・要望
        - 困っている点・問題
        - 質問・不明点
        - その他
    validations:
      required: true

  - type: textarea
    id: specific-content
    attributes:
      label: 具体的な内容・トピック
      description: カリキュラムの中でも特にどの部分についてですか？
      placeholder: 例：Day 2のデータ分析セッション、プロンプトエンジニアリング講座、Scratch Jr.実習、等

  - type: textarea
    id: feedback-detail
    attributes:
      label: 詳細なフィードバック
      description: 具体的なご意見・ご感想をお聞かせください
      placeholder: |
        - どの点が良かった／困った
        - どのような改善があると良いか
        - 他に学びたい内容
        - 教材の分かりやすさ
        - 進行速度、等
    validations:
      required: true

  - type: dropdown
    id: participant-type
    attributes:
      label: あなたの立場
      description: どの立場からのフィードバックですか？
      options:
        - 受講生（大人）
        - 受講生（子ども）
        - 保護者
        - 講師・スタッフ
        - 見学者・体験者
        - その他
    validations:
      required: true

  - type: dropdown
    id: experience-level
    attributes:
      label: 受講前のスキルレベル
      description: カリキュラムを受ける前のAI・プログラミングスキルレベルは？
      options:
        - 初心者（全く触ったことがない）
        - 初級（少し触ったことがある）
        - 中級（基本的なことはできる）
        - 上級（かなり詳しい）
        - 専門家レベル

  - type: dropdown
    id: difficulty-level
    attributes:
      label: 難易度の感想
      description: カリキュラムの難易度はいかがでしたか？
      options:
        - とても簡単
        - 簡単
        - ちょうど良い
        - 難しい
        - とても難しい

  - type: dropdown
    id: pace
    attributes:
      label: 進行ペースの感想
      description: カリキュラムの進行速度はいかがでしたか？
      options:
        - とても遅い
        - 遅い
        - ちょうど良い
        - 速い
        - とても速い

  - type: textarea
    id: learning-outcome
    attributes:
      label: 学習成果・収穫
      description: 受講してどのような学びや気づきがありましたか？

  - type: textarea
    id: suggestions
    attributes:
      label: 改善提案・追加希望内容
      description: どのような改善や追加があると良いと思いますか？
      placeholder: |
        - 新しいトピック・技術の追加
        - 実習の増加・減少
        - 教材の改良
        - サポート体制の改善、等

  - type: dropdown
    id: overall-satisfaction
    attributes:
      label: 総合満足度
      description: 全体的な満足度を教えてください
      options:
        - 非常に満足
        - 満足
        - 普通
        - 不満
        - 非常に不満
    validations:
      required: true

  - type: dropdown
    id: recommendation
    attributes:
      label: 推奨度
      description: 友人・知人にこのカリキュラムを勧めたいですか？
      options:
        - 強く勧めたい
        - 勧めたい
        - どちらでもない
        - あまり勧めない
        - 勧めない

  - type: textarea
    id: additional-comments
    attributes:
      label: その他のコメント
      description: その他、お気づきの点やご要望があれば自由にお書きください