name: "✨ 機能追加・改善の提案"
description: "新機能の追加や既存機能の改善を提案してください"
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        ## 機能追加・改善の提案
        
        AI Creator Labをより良いサービスにするため、新機能の追加や改善のアイデアをお聞かせください。
        ユーザーの皆様からのご意見・ご要望をお待ちしています！

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: 事前確認
      description: 提案前に以下をご確認ください
      options:
        - label: 既存のIssueで同じ提案がされていないか確認しました
          required: true
        - label: ドキュメントを読んで、既に存在する機能でないか確認しました
          required: true

  - type: dropdown
    id: category
    attributes:
      label: カテゴリ
      description: どの領域の機能追加・改善ですか？
      options:
        - 大人向けAIスクール
        - 子ども向けスクール（AI Kids Lab）
        - 法人向けサービス
        - ウェブサイト・UI/UX
        - カリキュラム・教材
        - 管理・運営システム
        - コミュニティ機能
        - その他
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題・ニーズ
      description: どのような課題や不便さを感じていますか？
      placeholder: 例：受講生の学習進捗を把握しにくい、予約システムが使いにくい、等
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: どのような機能があれば課題を解決できると思いますか？
      placeholder: 例：学習ダッシュボード機能、カレンダー連携、等
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 機能の詳細
      description: 提案する機能について、できるだけ具体的に説明してください
      placeholder: |
        - どのような画面・操作フローを想定しているか
        - どのようなデータを表示・管理したいか
        - 既存の機能とどのように連携するか

  - type: dropdown
    id: user-type
    attributes:
      label: 主な利用者
      description: この機能を主に誰が使用しますか？
      options:
        - 受講生（大人）
        - 受講生（子ども）
        - 保護者
        - 講師・スタッフ
        - 管理者
        - 法人クライアント
        - すべてのユーザー
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: 期待される効果・メリット
      description: この機能が実装されることで、どのような効果・メリットがありますか？
      placeholder: |
        - ユーザー体験の向上
        - 運営効率の改善
        - 新しい価値の提供
        - 問題解決、等

  - type: textarea
    id: examples
    attributes:
      label: 参考例・競合サービス
      description: 参考になるサービスやツール、実装例があれば教えてください

  - type: dropdown
    id: priority
    attributes:
      label: 優先度（あなたにとって）
      description: この機能はあなたにとってどの程度重要ですか？
      options:
        - 低（あれば便利だが、なくても困らない）
        - 中（あると明らかに体験が向上する）
        - 高（これがないと困る・使いにくい）
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: 実装時期の希望
      description: いつ頃実装されると良いですか？
      options:
        - いつでも良い
        - 3ヶ月以内
        - 1ヶ月以内
        - 緊急

  - type: textarea
    id: additional
    attributes:
      label: 追加情報・その他
      description: その他、機能の実装に役立ちそうな情報があれば教えてください

  - type: checkboxes
    id: contribution
    attributes:
      label: 貢献について
      description: この機能の実装について（任意）
      options:
        - label: 実装に協力したい（テスト・フィードバック等）
        - label: 技術的な実装に参加したい
        - label: 資料作成・ドキュメント化に協力したい